# Generated by Django 4.2.27 on 2026-01-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codigo_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('codigo_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rubro', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('codigo_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubRubro',
            fields=[
                ('codigo_subrubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subrubro', models.CharField(max_length=100)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subrubros', to='gestion.rubro')),
            ],
            options={
                'unique_together': {('nombre_subrubro', 'rubro')},
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('codigo_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.provincia')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codigo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cuil', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=150)),
                ('descripcion_articulo', models.TextField(blank=True)),
                ('art_precio_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('art_precio', models.DecimalField(decimal_places=2, help_text='Precio de venta', max_digits=12)),
                ('art_imagen', models.ImageField(blank=True, null=True, upload_to='articulos/')),
                ('art_stock', models.IntegerField(default=0)),
                ('art_bulto', models.BooleanField(default=False)),
                ('art_iva', models.DecimalField(decimal_places=2, help_text='IVA en porcentaje. ej: 21.00', max_digits=5)),
                ('art_precio_neto', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('art_precio_final', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.marca')),
                ('subrubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.subrubro')),
            ],
        ),
    ]
