# Generated by Django 4.2.27 on 2026-01-09 18:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_clientes_fecha_creacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='historial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('codigo_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(choices=[('P', 'Pendiente'), ('F', 'Facturado'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('forma_pago_pedido', models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de Credito'), ('TD', 'Tarjeta de Debito'), ('TR', 'Trasferencia')], max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('detalle_pedido_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_pedido_cantidad', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('detalle_pedido_precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle_pedido_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detalle_pedido_subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.pedidos')),
            ],
        ),
    ]
