# Generated by Django 4.2.27 on 2026-01-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_usuario_historial_pedidos_detallepedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='art_bulto',
            new_name='bulto_articulo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='art_imagen',
            new_name='imagen_articulo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='art_iva',
            new_name='iva_articulo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='art_precio',
            new_name='precio_articulo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='art_precio_final',
            new_name='precio_final',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='art_precio_neto',
            new_name='precio_neto',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='art_precio_original',
            new_name='precio_original_articulo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='art_stock',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='documento',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
