# Generated by Django 4.2.27 on 2026-01-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_art_bulto_articulo_bulto_articulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='precio_neto',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='detalle_pedido_precio',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
