# Generated by Django 4.2.27 on 2026-01-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_articulo_precio_neto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='precio_final',
            new_name='precio_con_iva',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='precio_original_articulo',
            new_name='precio_neto',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='bulto_articulo',
            new_name='vende_por_bulto',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='imagen_articulo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio_articulo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stock',
        ),
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock_unidades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidades_por_bulto',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='iva_articulo',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=5),
        ),
    ]
