# Generated by Django 4.2.27 on 2026-01-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rename_precio_final_articulo_precio_con_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre_articulo',
            field=models.CharField(max_length=100),
        ),
    ]
