# Generated by Django 4.2.7 on 2026-01-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rename_activo_articulo_art_acti_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='art_piva',
            new_name='art_pfin',
        ),
    ]
