# Generated by Django 4.2.7 on 2026-01-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_rename_art_piva_articulo_art_pfin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('fav_codi', models.AutoField(primary_key=True, serialize=False)),
                ('fav_fecha', models.DateTimeField(auto_now_add=True)),
                ('art_codi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.articulo')),
                ('cli_codi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='gestion.clientes')),
            ],
            options={
                'unique_together': {('cli_codi', 'art_codi')},
            },
        ),
    ]
