# Generated by Django 4.2.7 on 2026-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_cuil',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_dire',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_doc',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_tele',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
