# Generated by Django 4.2.7 on 2026-01-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_clientes_cli_cuil_alter_clientes_cli_dire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_dest',
            field=models.BooleanField(default=False),
        ),
    ]
