# Generated by Django 4.2.7 on 2026-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_articulo_art_dest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='art_dest',
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_img',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
    ]
