# Generated by Django 4.2.7 on 2026-01-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_articulo_art_dest_articulo_art_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=21, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('gen_codi', models.AutoField(primary_key=True, serialize=False)),
                ('gen_iva', models.CharField(choices=[('0', '0% (Exento)'), ('10.5', '10,5%'), ('21', '21%'), ('27', '27%')], default='21', max_length=5)),
                ('gen_nomb', models.CharField(max_length=100)),
                ('gen_raz', models.CharField(blank=True, max_length=150)),
                ('gen_logo', models.ImageField(blank=True, null=True, upload_to='general/')),
                ('gen_cuit', models.CharField(max_length=20)),
                ('gen_ingb', models.CharField(blank=True, max_length=30)),
                ('gen_razon', models.CharField(max_length=150)),
                ('gen_dire', models.CharField(blank=True, max_length=150)),
                ('gen_tele', models.CharField(blank=True, max_length=20)),
                ('gen_emai', models.EmailField(blank=True, max_length=254)),
                ('gen_loc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.localidad')),
            ],
        ),
    ]
