# Generated by Django 4.2.7 on 2026-01-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_articulo_art_iva_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='art_iva',
        ),
    ]
