# Generated by Django 4.2.7 on 2026-01-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_articulo_art_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='gen_iva',
            field=models.CharField(blank=True, choices=[('0', '0% (Exento)'), ('10.5', '10,5%'), ('21', '21%'), ('27', '27%')], help_text='Dejar en blanco para usar el IVA general', max_length=5, null=True),
        ),
    ]
