# Generated by Django 4.2.7 on 2026-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_articulo_gen_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='gen_iva',
            field=models.CharField(choices=[('21', '21%'), ('27', '27%'), ('10.5', '10,5%'), ('0', '0% (Exento)')], default='21', help_text='IVA del artículo', max_length=5),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_iva',
            field=models.CharField(choices=[('21', '21%'), ('27', '27%'), ('10.5', '10,5%'), ('0', '0% (Exento)')], default='21', max_length=5),
        ),
    ]
