# Generated by Django 4.2.27 on 2026-01-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_remove_general_gen_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ped_exportado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ped_fech_export',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
