# Generated by Django 4.2.27 on 2026-01-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_pedidos_ped_exportado_pedidos_ped_fech_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='ped_exportado',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ped_export',
            field=models.BooleanField(default=False, help_text='Indica si el pedido ya fue exportado a Genexus'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fech_export',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que el pedido fue exportado', null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fpag',
            field=models.CharField(choices=[('EF', 'ctiEfevo'), ('TC', 'Tarjeta de Credito'), ('TD', 'Tarjeta de Debito'), ('TR', 'Trasferencia')], max_length=2),
        ),
    ]
