# Generated by Django 4.2.27 on 2026-01-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_remove_pedidos_ped_exportado_pedidos_ped_export_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fpag',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de Credito'), ('TD', 'Tarjeta de Debito'), ('TR', 'Trasferencia')], max_length=2),
        ),
    ]
