# Generated by Django 4.2.27 on 2026-01-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_pedidos_ped_fpag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='ped_export',
            new_name='ped_exp',
        ),
        migrations.RenameField(
            model_name='pedidos',
            old_name='ped_fech_export',
            new_name='ped_fech_exp',
        ),
    ]
