# Generated by Django 4.2.7 on 2026-01-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_rename_ped_export_pedidos_ped_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='gen_cuit',
            field=models.CharField(default='00-00000000-0', max_length=20),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_dire',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_emai',
            field=models.EmailField(blank=True, default='contacto@debandi.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_ingb',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.localidad'),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_logo',
            field=models.ImageField(blank=True, default='general/logo-debandi.svg', null=True, upload_to='general/'),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_nomb',
            field=models.CharField(default='Debandi', max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_raz',
            field=models.CharField(blank=True, default='Debandi Distribuciones', max_length=150),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_razon',
            field=models.CharField(default='Responsable Inscripto', max_length=150),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_tele',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
