# Generated by Django 4.2.7 on 2026-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_general_gen_cuit_alter_general_gen_dire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='mar_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
