# Generated by Django 4.2.7 on 2026-01-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_alter_marca_mar_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='mar_codi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
