# Generated by Django 4.2.7 on 2026-01-29 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_alter_marca_mar_codi'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_fchc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_fmod',
            field=models.DateTimeField(auto_now=True, help_text='Última modificación'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_org',
            field=models.CharField(choices=[('ADMIN', 'Admin Django'), ('SCRIPT', 'Script automático'), ('API', 'API')], default='ADMIN', max_length=20),
        ),
    ]
