# Generated by Django 4.2.7 on 2026-01-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_articulo_art_fchc_articulo_art_fmod_articulo_art_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='sub_codi',
            new_name='sru_codi',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cli_fcre',
        ),
    ]
