# Generated by Django 4.2.7 on 2026-01-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_rename_sub_codi_articulo_sru_codi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='dpe_desc',
            new_name='dpe_des',
        ),
        migrations.RemoveField(
            model_name='general',
            name='gen_ingb',
        ),
        migrations.RemoveField(
            model_name='general',
            name='gen_razon',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usu_act',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usu_hist',
        ),
    ]
