# Generated by Django 4.2.7 on 2026-01-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_rename_dpe_desc_detallepedido_dpe_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='gen_color',
            field=models.CharField(choices=[('#a0d8d8', 'Celeste (actual)'), ('#3b82f6', 'Azul'), ('#10b981', 'Verde'), ('#f97316', 'Naranja'), ('#ef4444', 'Rojo'), ('#8b5cf6', 'Púrpura'), ('#6366f1', 'Índigo'), ('#ec4899', 'Rosa'), ('#14b8a6', 'Teal'), ('#6b7280', 'Gris')], default='#a0d8d8', help_text='Color principal de la interfaz', max_length=7),
        ),
    ]
