# Generated by Django 4.2.7 on 2026-01-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_general_gen_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='gen_color',
            field=models.CharField(choices=[('#8cced9', '🔵 Celeste (Predeterminado)'), ('#3b82f6', '🔵 Azul'), ('#10b981', '🟢 Verde'), ('#f59e0b', '🟡 Ámbar'), ('#ef4444', '🔴 Rojo'), ('#8b5cf6', '🟣 Púrpura'), ('#ec4899', '🩷 Rosa'), ('#6366f1', '🔷 Índigo')], default='#8cced9', help_text='Color principal de la aplicación', max_length=7),
        ),
    ]
