# Generated by Django 4.2.7 on 2026-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_alter_general_gen_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='gen_color',
            field=models.CharField(default='#8cced9', help_text='Color principal de la aplicación (formato HEX)', max_length=7),
        ),
    ]
