# Generated by Django 4.2.7 on 2026-01-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_alter_general_gen_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='gen_color',
            new_name='gen_colo',
        ),
    ]
