# Generated by Django 4.2.7 on 2026-01-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_rename_gen_color_general_gen_colo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cli_pswd',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_rexp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_rtok',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
