# Generated by Django 4.2.7 on 2026-02-02 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_clientes_cli_pswd_clientes_cli_rexp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='dpe_prec',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('art_codi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.articulo')),
                ('cli_codi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='gestion.clientes')),
            ],
            options={
                'ordering': ['-fecha_actualizado'],
                'unique_together': {('cli_codi', 'art_codi')},
            },
        ),
    ]
