# Generated by Django 4.2.7 on 2026-02-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_alter_detallepedido_dpe_prec_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='art_pfin_guardado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='art_pnet_guardado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
