# Generated by Django 4.2.7 on 2026-02-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0036_carritoitem_art_pfin_guardado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='art_pfin_guardado',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='art_pnet_guardado',
        ),
    ]
