# Generated by Django 4.2.7 on 2026-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0037_remove_carritoitem_art_pfin_guardado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='precio_guardado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio final guardado al momento de agregar', max_digits=10),
        ),
    ]
