# Generated by Django 4.2.7 on 2026-02-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_carritoitem_precio_guardado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='precio_guardado',
        ),
    ]
