# Generated by Django 4.2.7 on 2026-02-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_remove_carritoitem_precio_guardado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='art_pfin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='art_pnet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
