# Generated by Django 4.2.7 on 2026-02-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_carritoitem_art_pfin_carritoitem_art_pnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_exp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_fech_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fpag',
            field=models.CharField(choices=[('CDO', 'Contado'), ('CTC', 'Cuenta Corriente'), ('CHQ', 'Cheque')], max_length=3),
        ),
    ]
