# Generated by Django 4.2.7 on 2026-02-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0041_articulo_art_exp_articulo_art_fech_exp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='art_fech_exp',
            new_name='art_fexp',
        ),
    ]
