# Generated by Django 4.2.7 on 2026-02-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_rename_art_fech_exp_articulo_art_fexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_exp',
            field=models.BooleanField(default=False, help_text='Indica si el/o los articulos ya fueron exportado a BrixSoft(Genexus)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_fexp',
            field=models.DateTimeField(blank=True, help_text='Indica la fecha que se exportaron los articulos', null=True),
        ),
    ]
