# Generated by Django 4.2.7 on 2026-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0043_alter_articulo_art_exp_alter_articulo_art_fexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cli_exp',
            field=models.BooleanField(default=False, help_text='Indica si el/o los clientes ya fueron exportado a BrixSoft(Genexus)'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_fexp',
            field=models.DateTimeField(blank=True, help_text='Indica la fecha que se exportaron los clientes', null=True),
        ),
    ]
