# Generated by Django 4.2.7 on 2026-02-05 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0044_clientes_cli_exp_clientes_cli_fexp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cli_freg',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_fchc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_fmod',
            field=models.DateTimeField(auto_now=True, help_text='Última modificación'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_org',
            field=models.CharField(choices=[('ADMIN', 'Admin Django'), ('SCRIPT', 'Script automático'), ('API', 'API')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_exp',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ya fue exportado a BrixSoft (GeneXus)'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_fexp',
            field=models.DateTimeField(blank=True, help_text='Fecha de exportación a GeneXus', null=True),
        ),
    ]
