# Generated by Django 4.2.7 on 2026-02-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0045_remove_clientes_cli_freg_clientes_cli_fchc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='art_stkm',
            new_name='art_stkmax',
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_cint',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_depo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_stkmin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='sru_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.subrubro'),
        ),
    ]
