# Generated by Django 4.2.7 on 2026-02-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0046_rename_art_stkm_articulo_art_stkmax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
