# Generated by Django 4.2.7 on 2026-02-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0047_articulo_art_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
