# Generated by Django 4.2.7 on 2026-02-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0048_alter_articulo_art_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_mext',
            field=models.BooleanField(default=False, help_text='Marcar si el precio está en moneda extranjera (USD)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_depo',
            field=models.CharField(choices=[('DEPOSITO_ABAJO', 'Depósito Abajo'), ('DEPOSITO_ARRIBA', 'Depósito Arriba'), ('DEPOSITO_ENFRENTE', 'Depósito Enfrente'), ('PRINCIPAL', 'Principal'), ('SIN_DEFINIR', 'Sin Definir')], default='SIN_DEFINIR', max_length=30),
        ),
    ]
