# Generated by Django 4.2.7 on 2026-02-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0049_articulo_art_mext_alter_articulo_art_depo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='art_stku',
            new_name='art_stkp',
        ),
    ]
