# Generated by Django 4.2.7 on 2026-03-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0050_rename_art_stku_articulo_art_stkp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='mar_codi',
            field=models.ForeignKey(default=12882, on_delete=django.db.models.deletion.PROTECT, to='gestion.marca'),
        ),
    ]
