# Generated by Django 4.2.7 on 2026-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0051_alter_articulo_mar_codi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('bco_codi', models.AutoField(primary_key=True, serialize=False)),
                ('bco_nomb', models.CharField(max_length=100)),
                ('bco_titu', models.CharField(max_length=100)),
                ('bco_cuit', models.CharField(max_length=20)),
                ('bco_tip', models.CharField(choices=[('CAJA_AHORRO', 'Caja de Ahorro'), ('CUENTA_CORRIENTE', 'Cuenta Corriente'), ('CUENTA_VISA', 'Cuenta Visa')], default='CAJA_AHORRO', max_length=20)),
                ('bco_num', models.CharField(max_length=50)),
                ('bco_cbu', models.CharField(max_length=22, unique=True)),
                ('bco_ali', models.CharField(max_length=50, unique=True)),
                ('bco_acti', models.BooleanField(default=True)),
                ('bco_obs', models.TextField(blank=True, null=True)),
                ('bco_fchc', models.DateTimeField(auto_now_add=True)),
                ('bco_fmod', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['-bco_acti', 'bco_nomb'],
            },
        ),
    ]
