# Generated by Django 4.2.7 on 2026-03-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0052_cuentabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='bco_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='gestion.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fpag',
            field=models.CharField(choices=[('CDO', 'Contado'), ('CTC', 'Cuenta Corriente'), ('CHQ', 'Cheque'), ('MP', 'Mercado Pago')], max_length=3),
        ),
    ]
