# Generated by Django 4.2.7 on 2026-03-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0053_pedidos_bco_codi_alter_pedidos_ped_fpag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='ped_esta',
            field=models.CharField(choices=[('P', 'Pendiente'), ('PA', 'Pagado'), ('F', 'Facturado'), ('C', 'Cancelado')], default='P', max_length=2),
        ),
    ]
