# Generated by Django 4.2.7 on 2026-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0054_alter_pedidos_ped_esta'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_visw',
            field=models.BooleanField(default=True, help_text='Marcar para que el artículo sea visible en la web'),
        ),
    ]
