# Generated by Django 4.2.7 on 2026-03-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0055_articulo_art_visw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_exp',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ya fue exportado a BrixSoft'),
        ),
        migrations.CreateModel(
            name='LegajoPersonal',
            fields=[
                ('per_codi', models.AutoField(primary_key=True, serialize=False)),
                ('per_nomb', models.CharField(max_length=100)),
                ('per_doc', models.CharField(max_length=15, unique=True)),
                ('per_fnac', models.DateField(blank=True, null=True)),
                ('per_emai', models.EmailField(blank=True, max_length=254)),
                ('per_tele', models.CharField(blank=True, max_length=20)),
                ('per_fchc', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('per_fmod', models.DateTimeField(auto_now=True, help_text='Última modificación')),
                ('loc_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legajos', to='gestion.localidad')),
            ],
            options={
                'verbose_name': 'Legajo Personal',
                'verbose_name_plural': 'Legajos Personales',
                'ordering': ['per_nomb'],
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='per_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.legajopersonal'),
        ),
    ]
