# Generated by Django 4.2.7 on 2026-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0056_alter_clientes_cli_exp_legajopersonal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legajopersonal',
            name='per_tipo',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('RESPONSABLE', 'Responsable'), ('OTRO', 'Otro')], default='OTRO', max_length=15),
        ),
    ]
