# Generated by Django 4.2.7 on 2026-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0057_legajopersonal_per_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legajopersonal',
            name='per_doc',
        ),
        migrations.AlterField(
            model_name='legajopersonal',
            name='per_tipo',
            field=models.CharField(choices=[('C', 'Cliente'), ('P', 'Proveedor'), ('O', 'Otro')], help_text='Tipo de persona', max_length=1),
        ),
    ]
