# Generated by Django 4.2.7 on 2026-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0058_remove_legajopersonal_per_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_emai',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='legajopersonal',
            name='per_tipo',
            field=models.CharField(choices=[('C', 'Cliente'), ('P', 'Proveedor'), ('O', 'Otro')], help_text='Tipo de Responsable', max_length=1),
        ),
    ]
