# Generated by Django 4.2.7 on 2026-03-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0059_alter_clientes_cli_emai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legajopersonal',
            name='per_bar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legajopersonal',
            name='per_cuit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='legajopersonal',
            name='per_doc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='legajopersonal',
            name='per_dom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legajopersonal',
            name='per_emai',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='legajopersonal',
            name='per_nomb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legajopersonal',
            name='per_tipo',
            field=models.CharField(blank=True, choices=[('C', 'Cliente'), ('P', 'Proveedor'), ('O', 'Otro')], help_text='Tipo de Responsable', max_length=1, null=True),
        ),
    ]
