# Generated by Django 4.2.7 on 2026-03-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0060_legajopersonal_per_bar_legajopersonal_per_cuit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='per_codi',
        ),
        migrations.RemoveField(
            model_name='legajopersonal',
            name='per_tipo',
        ),
        migrations.AddField(
            model_name='legajopersonal',
            name='cli_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legajos_personales', to='gestion.clientes'),
        ),
    ]
