# Generated by Django 4.2.7 on 2026-03-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0061_remove_clientes_per_codi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='cli_cuil',
            new_name='cli_cuit',
        ),
    ]
