# Generated by Django 4.2.7 on 2026-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0062_rename_cli_cuil_clientes_cli_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cli_bar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
