# Generated by Django 4.2.7 on 2026-03-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0063_clientes_cli_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('per_codi', models.AutoField(primary_key=True, serialize=False)),
                ('per_nomb', models.CharField(blank=True, max_length=100, null=True)),
                ('per_doc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('per_fnac', models.DateField(blank=True, null=True)),
                ('per_emai', models.EmailField(blank=True, max_length=254, null=True)),
                ('per_tele', models.CharField(blank=True, max_length=20)),
                ('per_dom', models.CharField(blank=True, max_length=100, null=True)),
                ('per_bar', models.CharField(blank=True, max_length=100, null=True)),
                ('per_cuit', models.CharField(blank=True, max_length=10, null=True)),
                ('per_fchc', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('per_fmod', models.DateTimeField(auto_now=True, help_text='Última modificación')),
                ('cli_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to='gestion.clientes')),
                ('loc_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to='gestion.localidad')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['per_nomb'],
            },
        ),
        migrations.DeleteModel(
            name='LegajoPersonal',
        ),
    ]
