# Generated by Django 4.2.7 on 2026-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0065_rename_fields_vendedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['ven_nomb'], 'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
    ]
