# Generated by Django 4.2.7 on 2026-03-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0066_alter_vendedor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='ven_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.vendedor'),
        ),
    ]
