# Generated by Django 4.2.7 on 2026-03-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0066_remove_vendedor_cli_codi'),
        ('gestion', '0067_clientes_ven_codi'),
    ]

    operations = [
    ]
