# Generated by Django 4.2.7 on 2026-03-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0068_merge_20260305_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ven_actv',
            field=models.BooleanField(default=False, help_text='Activado por admin para usar el panel'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ven_pass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ven_perf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ven_usua',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
