# Generated by Django 4.2.7 on 2026-03-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0069_vendedor_ven_actv_vendedor_ven_pass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_actv',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_pass',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_perf',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_usua',
        ),
    ]
