# Generated by Django 4.2.7 on 2026-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0070_remove_vendedor_ven_actv_remove_vendedor_ven_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ven_actv',
            field=models.BooleanField(default=False, help_text='Vendedor activo para login'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ven_pass',
            field=models.CharField(blank=True, help_text='Contraseña hasheada', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ven_usua',
            field=models.CharField(blank=True, help_text='Usuario para login', max_length=50, null=True, unique=True),
        ),
    ]
