# Generated by Django 4.2.7 on 2026-04-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0071_vendedor_ven_actv_vendedor_ven_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cli_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion.clientes'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fpag',
            field=models.CharField(choices=[('CDO', 'Contado'), ('CTC', 'Cuenta Corriente'), ('CHQ', 'Cheque')], max_length=3),
        ),
        migrations.AlterField(
            model_name='subrubro',
            name='rub_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subrubro', to='gestion.rubro'),
        ),
        migrations.CreateModel(
            name='ClienteToken',
            fields=[
                ('tok_codi', models.AutoField(primary_key=True, serialize=False)),
                ('tok_valo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tok_crea', models.DateTimeField(auto_now_add=True)),
                ('tok_acti', models.BooleanField(default=True)),
                ('cli_codi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='gestion.clientes')),
            ],
        ),
    ]
