# Generated by Django 4.2.7 on 2026-04-27 19:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0072_alter_pedidos_cli_codi_alter_pedidos_ped_fpag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['art_nomb'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='carritoitem',
            options={'ordering': ['-carr_fmod'], 'verbose_name': 'Carrito Item', 'verbose_name_plural': 'Carrito Items'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['cli_nomb'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'ordering': ['dpe_ped', 'dpe_codi'], 'verbose_name': 'Detalle Pedido', 'verbose_name_plural': 'Detalles Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='favoritos',
            options={'ordering': ['-fav_fecha'], 'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'General', 'verbose_name_plural': 'General'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['pci_codi', 'loc_nomb'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['mar_nomb'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'ordering': ['-ped_codi'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['pci_nomb'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='rubro',
            options={'ordering': ['rub_nomb'], 'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
        migrations.AlterModelOptions(
            name='subrubro',
            options={'ordering': ['rub_codi', 'sru_nomb'], 'verbose_name': 'Sub-rubro', 'verbose_name_plural': 'Sub-rubros'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['usu_nomb'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['zon_nomb'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.RenameField(
            model_name='carritoitem',
            old_name='fecha_agregado',
            new_name='carr_fech',
        ),
        migrations.RenameField(
            model_name='carritoitem',
            old_name='fecha_actualizado',
            new_name='carr_fmod',
        ),
        migrations.RenameField(
            model_name='carritoitem',
            old_name='art_pfin',
            new_name='carr_pfin',
        ),
        migrations.RenameField(
            model_name='carritoitem',
            old_name='art_pnet',
            new_name='carr_pnet',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='dpe_deta',
            new_name='dpe_ped',
        ),
        migrations.AlterUniqueTogether(
            name='subrubro',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cli_pswd',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='ped_fech_exp',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='ven_pass',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carr_cant',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carr_codi',
            field=models.IntegerField(default=0, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_celu',
            field=models.CharField(blank=True, help_text='Celular', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_clav',
            field=models.CharField(blank=True, help_text='Contraseña/Clave (hasheada)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_estc',
            field=models.CharField(blank=True, help_text='Estado civil', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_fnac',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_ndoc',
            field=models.CharField(blank=True, help_text='Número de documento', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_ocup',
            field=models.CharField(blank=True, help_text='Ocupación', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_tdoc',
            field=models.CharField(default='DNI', help_text='Tipo de documento', max_length=20),
        ),
        migrations.AddField(
            model_name='general',
            name='gen_loge',
            field=models.ImageField(blank=True, help_text='Logo de BrixSoft', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='loc_cpos',
            field=models.CharField(blank=True, help_text='Código postal', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ped_fexp',
            field=models.DateTimeField(blank=True, help_text='Fecha de exportación', null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ven_clav',
            field=models.CharField(blank=True, help_text='Contraseña/Clave (hasheada)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_acti',
            field=models.BooleanField(default=True, help_text='Artículo activo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_cint',
            field=models.CharField(blank=True, help_text='Código interno', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_desc',
            field=models.TextField(blank=True, help_text='Descripción del artículo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_exp',
            field=models.BooleanField(default=False, help_text='Exportado a GeneXus'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_fchc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_fexp',
            field=models.DateTimeField(blank=True, help_text='Fecha de exportación', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_fmod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_mext',
            field=models.BooleanField(default=False, help_text='Precio en moneda extranjera (USD)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_pfin',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Precio final con IVA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_pnet',
            field=models.DecimalField(decimal_places=2, help_text='Precio neto', max_digits=12),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_sku',
            field=models.CharField(blank=True, help_text='SKU', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_stkmax',
            field=models.PositiveIntegerField(default=0, help_text='Stock máximo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_stkmin',
            field=models.PositiveIntegerField(default=0, help_text='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_stkp',
            field=models.PositiveIntegerField(default=0, help_text='Stock principal'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_ubul',
            field=models.PositiveIntegerField(default=1, help_text='Unidades por bulto'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_visw',
            field=models.BooleanField(default=True, help_text='Visible en web'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_xbul',
            field=models.BooleanField(default=False, help_text='Por bulto/pack'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='mar_codi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='gestion.marca'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='sru_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='gestion.subrubro'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_bar',
            field=models.CharField(blank=True, help_text='Barrio', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_cuit',
            field=models.CharField(blank=True, help_text='CUIT', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_dire',
            field=models.CharField(blank=True, help_text='Dirección', max_length=150),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_doc',
            field=models.CharField(blank=True, help_text='Documento (legado)', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_emai',
            field=models.EmailField(blank=True, help_text='Email', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_exp',
            field=models.BooleanField(default=False, help_text='Exportado a BrixSoft'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_fchc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_fexp',
            field=models.DateTimeField(blank=True, help_text='Fecha de exportación', null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_fmod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_nomb',
            field=models.CharField(help_text='Nombre del cliente', max_length=150),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_rexp',
            field=models.DateTimeField(blank=True, help_text='Expiración del token', null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_rtok',
            field=models.CharField(blank=True, help_text='Token de recuperación', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_tele',
            field=models.CharField(blank=True, help_text='Teléfono', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='loc_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='gestion.localidad'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ven_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='gestion.vendedor'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='bco_ali',
            field=models.CharField(help_text='Alias CBU', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='bco_cbu',
            field=models.CharField(help_text='Código Bancario Único', max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='bco_obs',
            field=models.TextField(blank=True, help_text='Observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='bco_titu',
            field=models.CharField(help_text='Titular de la cuenta', max_length=100),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='art_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_pedidos', to='gestion.articulo'),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='art_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_favoritos', to='gestion.articulo'),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_colo',
            field=models.CharField(default='#8cced9', help_text='Color principal (HEX)', max_length=7),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_cuit',
            field=models.CharField(default='00-00000000-0', help_text='CUIT de la empresa', max_length=20),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_dire',
            field=models.CharField(blank=True, help_text='Dirección', max_length=150),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_emai',
            field=models.EmailField(blank=True, default='contacto@debandi.com', help_text='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.localidad'),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_logo',
            field=models.ImageField(blank=True, help_text='Logo de Debandi', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_nomb',
            field=models.CharField(blank=True, help_text='Nombre de la empresa', max_length=150),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_raz',
            field=models.CharField(blank=True, default='Debandi Distribuciones', help_text='Razón social', max_length=150),
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_tele',
            field=models.CharField(blank=True, help_text='Teléfono', max_length=20),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='loc_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='pci_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='gestion.provincia'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='zon_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='gestion.zona'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='mar_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_exp',
            field=models.BooleanField(default=False, help_text='Exportado a GeneXus'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fpag',
            field=models.CharField(choices=[('CDO', 'Contado'), ('CTC', 'Cuenta Corriente'), ('CHQ', 'Cheque'), ('TRF', 'Transferencia')], max_length=3),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='pci_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='rub_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subrubro',
            name='rub_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subrubros', to='gestion.rubro'),
        ),
        migrations.AlterField(
            model_name='subrubro',
            name='sru_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usu_perf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usu_rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_actv',
            field=models.BooleanField(default=False, help_text='Vendedor activo'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_bar',
            field=models.CharField(blank=True, help_text='Barrio', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_cuit',
            field=models.CharField(blank=True, help_text='CUIT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_doc',
            field=models.CharField(blank=True, help_text='Documento', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_dom',
            field=models.CharField(blank=True, help_text='Domicilio', max_length=150),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_fchc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_fmod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_fnac',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_nomb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zona',
            name='zon_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='subrubro',
            unique_together={('rub_codi', 'sru_nomb')},
        ),
        migrations.DeleteModel(
            name='ClienteToken',
        ),
    ]
