# Generated by Django 4.2.7 on 2026-04-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0073_alter_articulo_options_alter_carritoitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='carr_codi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
