# Generated by Django 4.2.7 on 2026-05-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0074_remove_carritoitem_id_alter_carritoitem_carr_codi'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='gen_coti',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cotización', max_digits=12),
        ),
    ]
