# Generated by Django 4.2.7 on 2026-05-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0075_general_gen_coti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='art_cint',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='art_stkmax',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='art_stkmin',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='art_stkp',
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_cant',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_descu',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento', max_digits=12),
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_stk',
            field=models.PositiveIntegerField(default=0, help_text='Stock de artículos'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_depo',
            field=models.IntegerField(default=0, help_text='Depósito'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_tiva',
            field=models.DecimalField(decimal_places=2, default=21, help_text='IVA del artículo (%)', max_digits=5),
        ),
    ]
