# Generated by Django 4.2.7 on 2026-05-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0076_remove_articulo_art_cint_remove_articulo_art_stkmax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='bco_codi',
        ),
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('dpe_ped', 'art_codi')},
        ),
    ]
