# Generated by Django 4.2.7 on 2026-05-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0082_detallepedido_dpe_cant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'ordering': ['ped_codi', 'dpe_codi'], 'verbose_name': 'Detalle Pedido', 'verbose_name_plural': 'Detalles Pedidos'},
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='art_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_pedidos', to='gestion.articulo'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_esta',
            field=models.CharField(choices=[('P', 'Pendiente'), ('PR', 'Procesado')], default='P', max_length=2),
        ),
    ]
