# Generated by Django 4.2.7 on 2026-05-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0083_alter_detallepedido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_carru',
            field=models.BooleanField(default=False, help_text='Mostrar en carrusel de inicio'),
        ),
    ]
