# Generated by Django 4.2.7 on 2026-05-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0084_articulo_art_carru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fech',
            field=models.DateField(blank=True, help_text='Fecha del pedido', null=True),
        ),
    ]
