# Generated by Django 4.2.7 on 2026-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0085_alter_pedidos_ped_fech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='ped_esta',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='dpe_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
