# Generated by Django 4.2.7 on 2026-05-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0086_remove_pedidos_ped_esta_alter_detallepedido_dpe_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_acti',
            field=models.BooleanField(default=True, help_text='Artículo activo', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_carru',
            field=models.BooleanField(default=False, help_text='Mostrar en carrusel de inicio', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_depo',
            field=models.IntegerField(default=0, help_text='Depósito', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_desc',
            field=models.TextField(blank=True, help_text='Descripción del artículo', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_descu',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_mext',
            field=models.BooleanField(default=False, help_text='Precio en moneda extranjera (USD)', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_pnet',
            field=models.DecimalField(decimal_places=2, help_text='Precio neto', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_stk',
            field=models.PositiveIntegerField(default=0, help_text='Stock de artículos', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_tiva',
            field=models.DecimalField(decimal_places=2, default=21, help_text='IVA del artículo (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_ubul',
            field=models.PositiveIntegerField(default=1, help_text='Unidades por bulto', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_visw',
            field=models.BooleanField(default=True, help_text='Visible en web', null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_xbul',
            field=models.BooleanField(default=False, help_text='Por bulto/pack', null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_bar',
            field=models.CharField(blank=True, help_text='Barrio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_clav',
            field=models.CharField(blank=True, default='', help_text='Contraseña/Clave (hasheada)', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_dire',
            field=models.CharField(blank=True, help_text='Dirección', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_tdoc',
            field=models.CharField(default='DNI', help_text='Tipo de documento', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cli_tele',
            field=models.CharField(blank=True, help_text='Teléfono', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='loc_codi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='gestion.localidad'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='dpe_codi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_actv',
            field=models.BooleanField(default=False, help_text='Vendedor activo', null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_bar',
            field=models.CharField(blank=True, help_text='Barrio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_dom',
            field=models.CharField(blank=True, help_text='Domicilio', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_emai',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_fchc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_fmod',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ven_tele',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='zon_nomb',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
