# Generated by Django 4.2.7 on 2026-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0087_alter_articulo_art_acti_alter_articulo_art_carru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ped_hora',
            field=models.TimeField(blank=True, help_text='Hora del pedido', null=True),
        ),
    ]
