# Generated by Django 4.2.7 on 2026-05-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0088_pedidos_ped_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='art_cant',
        ),
    ]
