# Generated by Django 4.2.7 on 2026-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0089_remove_articulo_art_cant'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_palac',
            field=models.CharField(blank=True, help_text='Palabras clave para búsqueda (separadas por comas)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='art_pfin',
            field=models.DecimalField(decimal_places=2, help_text='Precio final con IVA', max_digits=12),
        ),
    ]
