# Generated by Django 4.2.7 on 2026-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0090_articulo_art_palac_alter_articulo_art_pfin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_palac',
            field=models.CharField(blank=True, help_text='Palabras clave para búsqueda si es complejo el art_nomb', max_length=255, null=True),
        ),
    ]
