# Generated by Django 4.2.7 on 2026-05-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0091_alter_articulo_art_palac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('reg_codi', models.AutoField(primary_key=True, serialize=False)),
                ('reg_nomb', models.CharField(help_text='Nombre del cliente', max_length=150)),
                ('reg_emai', models.EmailField(help_text='Email', max_length=254, unique=True)),
                ('reg_clav', models.CharField(help_text='Contraseña (hasheada)', max_length=128)),
                ('reg_fnac', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
                ('reg_tdoc', models.CharField(default='DNI', help_text='Tipo de documento', max_length=20)),
                ('reg_ndoc', models.CharField(blank=True, help_text='Número de documento', max_length=20, null=True)),
                ('reg_celu', models.CharField(blank=True, help_text='Celular', max_length=20, null=True)),
                ('reg_tele', models.CharField(blank=True, help_text='Teléfono', max_length=20, null=True)),
                ('reg_dire', models.CharField(blank=True, help_text='Dirección', max_length=150, null=True)),
                ('reg_bar', models.CharField(blank=True, help_text='Barrio', max_length=100, null=True)),
                ('reg_est', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', help_text='Estado del registro', max_length=20)),
                ('reg_fech', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro')),
                ('reg_frec', models.DateTimeField(blank=True, help_text='Fecha de revisión', null=True)),
                ('reg_obs', models.TextField(blank=True, help_text='Observaciones del admin', null=True)),
                ('loc_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='gestion.localidad')),
            ],
            options={
                'verbose_name': 'Registro de Cliente',
                'verbose_name_plural': 'Registros de Clientes',
                'ordering': ['-reg_fech'],
                'indexes': [models.Index(fields=['reg_est', '-reg_fech'], name='gestion_reg_reg_est_be73ed_idx'), models.Index(fields=['reg_emai'], name='gestion_reg_reg_ema_93a052_idx')],
            },
        ),
    ]
