# Generated by Django 4.2.7 on 2026-05-15 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0092_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-reg_fchc'], 'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.RemoveIndex(
            model_name='registro',
            name='gestion_reg_reg_est_be73ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='registro',
            name='gestion_reg_reg_ema_93a052_idx',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='loc_codi',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_bar',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_celu',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_dire',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_est',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_fech',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_fnac',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_frec',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_ndoc',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_obs',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_tdoc',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='reg_tele',
        ),
        migrations.AddField(
            model_name='registro',
            name='reg_apel',
            field=models.CharField(help_text='Apellido', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='reg_doc',
            field=models.CharField(default=1, help_text='Documento', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='reg_exp',
            field=models.BooleanField(default=False, help_text='Aprobado/Autorizado'),
        ),
        migrations.AddField(
            model_name='registro',
            name='reg_fchc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='reg_fmod',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_nomb',
            field=models.CharField(help_text='Nombre', max_length=150),
        ),
    ]
