# Generated by Django 4.2.7 on 2026-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0093_alter_registro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='reg_doc',
            field=models.CharField(help_text='Documento', max_length=8),
        ),
    ]
