# Generated by Django 4.2.7 on 2026-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0094_alter_registro_reg_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cli_acti',
            field=models.BooleanField(default=True, help_text='Cliente activo/de baja', null=True),
        ),
    ]
