# Generated by Django 4.2.7 on 2026-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0095_clientes_cli_acti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='reg_doc',
            field=models.IntegerField(help_text='Documento', max_length=8),
        ),
    ]
