# Generated by Django 4.2.7 on 2026-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0096_alter_registro_reg_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='reg_clie',
            field=models.BooleanField(default=False, help_text='Aprobado/Convertido a Cliente'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_exp',
            field=models.BooleanField(default=False, help_text='Exportado a GeneXus'),
        ),
    ]
