# Generated by Django 4.2.7 on 2026-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0097_registro_reg_clie_alter_registro_reg_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='reg_doc',
            field=models.IntegerField(help_text='Documento'),
        ),
    ]
