# Generated by Django 4.2.7 on 2026-05-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0098_alter_registro_reg_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='zon_codi',
        ),
    ]
