# Generated by Django 4.2.7 on 2026-05-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0099_remove_localidad_zon_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='ven_actv',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=0, help_text='Vendedor activo', null=True),
        ),
    ]
