# Generated by Django 4.2.7 on 2026-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0100_alter_vendedor_ven_actv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='ven_emai',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
