# Generated by Django 4.2.7 on 2026-05-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0101_alter_vendedor_ven_emai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cli_doc',
        ),
    ]
