# Generated by Django 4.2.7 on 2026-05-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0102_remove_clientes_cli_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='zon_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='gestion.zona'),
        ),
    ]
