# Generated by Django 4.2.7 on 2026-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0103_clientes_zon_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_clav',
            field=models.CharField(blank=True, help_text='Contraseña/Clave (hasheada)', max_length=128, null=True),
        ),
    ]
