# Generated by Django 4.2.7 on 2026-05-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0104_alter_clientes_cli_clav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_nomb',
            field=models.CharField(max_length=255),
        ),
    ]
