# Generated by Django 4.2.7 on 2026-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0105_alter_articulo_art_nomb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_emai',
            field=models.CharField(blank=True, help_text='Email', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_clie',
            field=models.BooleanField(default=False, help_text='Aprobado/NO aprobado por debandi'),
        ),
    ]
