# Generated by Django 4.2.7 on 2026-05-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0106_alter_clientes_cli_emai_alter_registro_reg_clie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_cuit',
            field=models.CharField(blank=True, help_text='CUIT', max_length=20, null=True),
        ),
    ]
