# Generated by Django 4.2.7 on 2026-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0107_alter_clientes_cli_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cli_desc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento cliente (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_prec1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio sugerido 1 (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_prec2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio sugerido 2 (%)', max_digits=5),
        ),
    ]
