# Generated by Django 4.2.7 on 2026-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0108_clientes_cli_desc_clientes_cli_prec1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cli_prec1',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cli_prec2',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_precs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio sugerido (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_precv',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio venta (%)', max_digits=5),
        ),
    ]
