# Generated by Django 4.2.7 on 2026-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0109_remove_clientes_cli_prec1_remove_clientes_cli_prec2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_pnet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio neto', max_digits=12, null=True),
        ),
    ]
