# Generated by Django 4.2.7 on 2026-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0111_rename_clientes_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('nov_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('nov_nomb', models.CharField(help_text='Nombre de la sección de novedades', max_length=100)),
                ('nov_bann', models.BooleanField(default=False, help_text='Mostrar banners de ofertas')),
                ('nov_prodr', models.BooleanField(default=False, help_text='Mostrar productos recomendados')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['nov_nomb'],
            },
        ),
        migrations.AlterField(
            model_name='general',
            name='gen_colo',
            field=models.CharField(default='#0A53BF', help_text='Color principal (HEX)', max_length=7),
        ),
    ]
