# Generated by Django 4.2.7 on 2026-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0112_novedades_alter_general_gen_colo'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='art_carru',
            field=models.ManyToManyField(blank=True, help_text='Artículos para mostrar como Nuevos Productos', related_name='en_novedades', to='gestion.articulo'),
        ),
    ]
