# Generated by Django 4.2.7 on 2026-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0113_novedades_art_carru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='art_carru',
            field=models.ManyToManyField(blank=True, help_text='Artículos para mostrar en carrusel de nuevos productos', related_name='en_novedades', to='gestion.articulo'),
        ),
    ]
