# Generated by Django 4.2.7 on 2026-06-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0114_alter_novedades_art_carru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedades',
            name='art_carru',
        ),
        migrations.AddField(
            model_name='novedades',
            name='art_carru',
            field=models.ForeignKey(blank=True, help_text='Artículo destacado en carrusel de nuevos productos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_novedades', to='gestion.articulo'),
        ),
    ]
