# Generated by Django 4.2.7 on 2026-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0116_articulo_art_prodr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_exp',
            field=models.BooleanField(default=False, help_text='Exportado a GeneXus'),
        ),
    ]
