# Generated by Django 4.2.7 on 2026-06-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0117_alter_clientes_cli_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='nov_fechf',
            field=models.DateField(blank=True, help_text='Fecha de final banner', null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='nov_fechi',
            field=models.DateField(blank=True, help_text='Fecha de inicio banner', null=True),
        ),
    ]
