# Generated by Django 4.2.7 on 2026-06-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0118_novedades_nov_fechf_novedades_nov_fechi'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='nov_desc',
            field=models.TextField(blank=True, help_text='Descripción del banner', null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='nov_img',
            field=models.ImageField(blank=True, help_text='Imagen del banner', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='nov_titl',
            field=models.CharField(blank=True, help_text='Título del banner', max_length=255, null=True),
        ),
    ]
