# Generated by Django 4.2.7 on 2026-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0119_novedades_nov_desc_novedades_nov_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedades',
            options={'ordering': ['-nov_fechi'], 'verbose_name': 'Novedad', 'verbose_name_plural': 'Novedades'},
        ),
        migrations.AddField(
            model_name='novedades',
            name='nov_acti',
            field=models.BooleanField(default=True, help_text='¿Mostrar esta novedad?'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='nov_cate',
            field=models.CharField(choices=[('nuevos_ingresos', 'Nuevos Ingresos'), ('promocion', 'Promoción'), ('oferta', 'Oferta'), ('destacado', 'Destacado'), ('otro', 'Otro')], default='otro', help_text='Categoría de la novedad', max_length=50),
        ),
    ]
