# Generated by Django 4.2.7 on 2026-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0120_alter_novedades_options_novedades_nov_acti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='reg_apel',
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_nomb',
            field=models.CharField(help_text='Nombre y Apellido', max_length=150),
        ),
    ]
