# Generated by Django 4.2.7 on 2026-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0121_remove_registro_reg_apel_alter_registro_reg_nomb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cli_acti',
            field=models.BooleanField(default=False, help_text='Cliente activo (requerido para iniciar sesión)', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_codi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
