# Generated by Django 4.2.7 on 2026-06-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0122_alter_clientes_cli_acti_alter_registro_reg_codi'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_cn',
            field=models.CharField(blank=True, help_text='Codigo Numerico', max_length=20, null=True),
        ),
    ]
