# Generated by Django 4.2.7 on 2026-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0123_articulo_art_cn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='art_img',
            new_name='art_img1',
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_img2',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='art_img3',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
    ]
