# Generated by Django 4.2.7 on 2026-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0124_rename_art_img_articulo_art_img1_articulo_art_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='dpe_pfin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio final congelado al procesar el pedido. Null mientras el pedido está pendiente (usa el precio actual del artículo)', max_digits=12, null=True),
        ),
    ]
