# Generated by Django 4.2.7 on 2026-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0125_detallepedido_dpe_pfin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_stk',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Stock de artículos', null=True),
        ),
    ]
