# Generated by Django 4.2.7 on 2026-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0126_art_stk_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='reg_clav',
            field=models.CharField(blank=True, help_text='Contraseña (hasheada)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_clie',
            field=models.BooleanField(blank=True, default=False, help_text='Aprobado/NO aprobado por debandi', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_doc',
            field=models.IntegerField(blank=True, help_text='Documento', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_emai',
            field=models.EmailField(blank=True, help_text='Email', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_nomb',
            field=models.CharField(blank=True, help_text='Nombre y Apellido', max_length=150, null=True),
        ),
    ]
