# Generated by Django 4.2.7 on 2026-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0127_alter_registro_reg_clav_alter_registro_reg_clie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='reg_celu',
            field=models.CharField(blank=True, help_text='Celular', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='reg_cuit',
            field=models.CharField(blank=True, help_text='CUIT', max_length=20, null=True),
        ),
    ]
