# Generated by Django 4.2.7 on 2026-08-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0128_registro_reg_celu_registro_reg_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='reg_clavf',
            field=models.CharField(blank=True, help_text='Contraseña sin hashear, tal cual la envía el front (uso interno para export a GeneXus)', max_length=128, null=True),
        ),
    ]
