# Generated by Django 4.2.7 on 2026-08-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0129_registro_reg_clavf'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='reg_civa',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('EX', 'Exento')], help_text='Condición frente al IVA', max_length=2, null=True),
        ),
    ]
