# Generated by Django 4.2.7 on 2026-08-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0130_registro_reg_civa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ven_gere',
            field=models.BooleanField(blank=True, default=False, help_text='Gerencia: habilita exportar cuenta corriente y facturas PDF (S=true, N/vacío=false)', null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='reg_civa',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('EX', 'Exento')], help_text='Condición de IVA', max_length=2, null=True),
        ),
    ]
