# Generated by Django 4.2.7 on 2026-08-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0133_articulo_art_visw_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ped_crea',
            field=models.CharField(blank=True, choices=[('clie', 'Cliente'), ('vend', 'Vendedor')], help_text='Quien creo el pedido: cliente o vendedor', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ped_edit',
            field=models.CharField(blank=True, choices=[('clie', 'Cliente'), ('vend', 'Vendedor')], help_text='Quien hizo la modificacion: cliente o vendedor', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ped_fechCr',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora creacion del pedido', null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ped_fechEd',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora modifcacion del pedido', null=True),
        ),
    ]
