# Generated by Django 4.2.7 on 2026-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0135_rename_gen_coti_general_gen_dola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='ped_crea',
            field=models.CharField(blank=True, choices=[('C', 'Cliente'), ('V', 'Vendedor')], help_text='Quien creo el pedido: cliente o vendedor', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_edit',
            field=models.CharField(blank=True, choices=[('C', 'Cliente'), ('V', 'Vendedor')], help_text='Quien hizo la modificacion: cliente o vendedor', max_length=10, null=True),
        ),
    ]
