# Generated by Django 4.2.7 on 2026-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0136_alter_pedidos_ped_crea_alter_pedidos_ped_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_cdol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Costo dolar', max_digits=12),
        ),
    ]
