# Generated by Django 4.2.7 on 2026-09-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0137_articulo_art_cdol'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='art_uti1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Margen (%)', max_digits=6, null=True),
        ),
    ]
