# Generated by Django 4.2.7 on 2026-09-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0138_articulo_art_uti1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_cdol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Costo dolar', max_digits=12, null=True),
        ),
    ]
