# Generated by Django 4.2.7 on 2026-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0139_alter_articulo_art_cdol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='art_descu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Descuento', max_digits=12, null=True),
        ),
    ]
