# Generated by Django 4.2.7 on 2026-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0140_articulo_art_descu_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ped_obse',
            field=models.CharField(blank=True, help_text='Obversaciones del pedido', max_length=150, null=True),
        ),
    ]
