# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0141_pedidos_ped_obse'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='ven_adm',
            field=models.BooleanField(blank=True, default=False, help_text='Vendedor Administrador: si es True, puede ver TODOS los clientes sin excepción, sin importar el vendedor asignado', null=True),
        ),
    ]
