# Generated by Django 4.2.7 on 2026-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0142_vendedor_ven_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='ped_obse',
            field=models.CharField(blank=True, help_text='Obversaciones del pedido', max_length=110, null=True),
        ),
    ]
