# Generated by Django 4.2.7 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0143_alter_pedidos_ped_obse'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='reg_direE',
            field=models.CharField(blank=True, help_text='Direccion Entrega', max_length=80, null=True),
        ),
    ]
