# Generated by Django 4.2.7 on 2026-09-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0144_registro_reg_direE'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='reg_codi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
