# Generated by Django 4.2.7 on 2026-10-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0145_alter_registro_reg_codi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='ven_codi',
            field=models.ForeignKey(blank=True, help_text='Vendedor que arma este carrito (vacío = el propio cliente)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='gestion.vendedor'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.UniqueConstraint(condition=models.Q(('ven_codi__isnull', True)), fields=('cli_codi', 'art_codi'), name='carrito_unico_cliente'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.UniqueConstraint(fields=('cli_codi', 'ven_codi', 'art_codi'), name='carrito_unico_vendedor'),
        ),
    ]
