# Generated by Django 4.2.7 on 2026-10-05 15:07

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def completar_dpe_pnet(apps, schema_editor):
    """
    Pedidos ya procesados antes de este cambio: tienen dpe_pfin congelado pero no el neto.
    Se estima el neto congelado con la misma proporción neto/final que tiene hoy el
    artículo (si el precio no cambió desde que se procesó, da exactamente art_pnet).
    Si el artículo no tiene precio final, se descuenta el IVA del artículo.
    """
    DetallePedido = apps.get_model('gestion', 'DetallePedido')
    pendientes = DetallePedido.objects.filter(
        dpe_pfin__isnull=False, dpe_pnet__isnull=True
    ).select_related('art_codi')

    a_actualizar = []
    for detalle in pendientes.iterator():
        art = detalle.art_codi
        pfin = Decimal(str(detalle.dpe_pfin))
        art_pfin = Decimal(str(art.art_pfin or 0))
        art_pnet = Decimal(str(art.art_pnet or 0))
        if art_pfin > 0:
            neto = pfin * art_pnet / art_pfin
        else:
            iva = Decimal(str(art.art_tiva)) if art.art_tiva else Decimal('21')
            neto = pfin / (1 + iva / 100)
        detalle.dpe_pnet = neto.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        a_actualizar.append(detalle)

    # bulk_update no dispara DetallePedido.save(), así no se recalcula ped_tota
    DetallePedido.objects.bulk_update(a_actualizar, ['dpe_pnet'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0146_carrito_por_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='dpe_pnet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio neto (sin IVA) congelado al procesar el pedido. Null mientras el pedido está pendiente (usa el precio actual del artículo)', max_digits=12, null=True),
        ),
        migrations.RunPython(completar_dpe_pnet, migrations.RunPython.noop),
    ]
